### PR TITLE
feat: add user_metadata to dedicated_server_install module

### PR DESCRIPTION
**Pull request by D0tty**
This field allows to push metadata during the intallation
i.e.: The ssh public key can be pushed as shown in the example

It's been tested on my end and should not cause any breaking change as it's not a requiered field and has no impact if not provided

### CODE REVIEW

**Comment by D0tty** [comment]
I took the liberty to take the commit from the branch `synthesio/fix_vps_display` so that the linting could pass

**Comment by tortuegenialez** [comment]
Can you link the documentation for this `user_metadata` list?
I can't find any explanation on the ovh console and I'm curious how you found that

**Comment by D0tty** [comment]
Yes it's a bit hidden, let me find that :wink:

**Comment by D0tty** [comment]
You can find the description of the field `userMetadata` on the [ovh API Console](https://eu.api.ovh.com/console/?section=%2Fdedicated%2Fserver&branch=v1#post-/dedicated/server/-serviceName-/install/start) 

and as for the special use of `sshKey` metadata I'll have to dig more I can't recall where I found it :cry:

**Pull request merged**
